#%RAML 1.0 Trait

usage:  Apply this trait to a GET method that supports ordering.
queryParameters:
      orderBy:
        description: |
          Order by field: <<fieldsList>>
        type: string
        required: false
      order:
        description: Order
        enum: [desc, asc]
        default: desc
        required: false